@baseUrl = http://localhost:3000
@urlPath = api

###
POST {{baseUrl}}/{{urlPath}}/store
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "uid": "2755113451",
  "name": "ASDFG",
  "cnt": 3,
  "giftId": 3
}

###
GET {{baseUrl}}/{{urlPath}}/store
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/store/3
Content-Type: application/json
Accept: application/json
withCredentials: true