export const WIN_RECORD: {
  name: string;
  date: string;
  reason: string;
  present: string;
}[] = [
  {
    name: "서재",
    date: "7/1",
    reason: "스토어 응모 당첨",
    present: "스타벅스 커피",
  },
  {
    name: "김영",
    date: "7/1",
    reason: "스토어 응모 당첨",
    present: "스타벅스 커피",
  },
  {
    name: "김유",
    date: "7/2",
    reason: "스토어 응모 당첨",
    present: "허쉬 초콜릿드링크",
  },
  {
    name: "김영",
    date: "7/2",
    reason: "스토어 응모 당첨",
    present: "허쉬 초콜릿드링크",
  },
  {
    name: "김예",
    date: "7/2",
    reason: "스토어 응모 당첨",
    present: "허쉬 초콜릿드링크",
  },
  {
    name: "송재",
    date: "7/3",
    reason: "홍보 이벤트 당첨",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "이승",
    date: "7/3",
    reason: "홍보 이벤트 당첨",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "김소",
    date: "7/3",
    reason: "홍보 이벤트 당첨",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "김예",
    date: "7/16",
    reason: "카페 추천 및 채택",
    present: "Mega 커피",
  },
  {
    name: "서재",
    date: "7/16",
    reason: "스터디 장소 조사",
    present: "할리스 10000원권",
  },
  {
    name: "이희",
    date: "7/20",
    reason: "오류 내용 피드백",
    present: "Mega 커피",
  },
  {
    name: "박유",
    date: "7/22",
    reason: "건의사항 제출",
    present: "딸기 요거트 스무디",
  },
  {
    name: "도형",
    date: "7/22",
    reason: "오류 피드백",
    present: "베스킨라빈스 싱글",
  },
  {
    name: "박무",
    date: "8/2",
    reason: "건의사항 제출",
    present: "굽네 오리지널 세트",
  },
  {
    name: "손희",
    date: "8/8",
    reason: "스토어 응모 당첨",
    present: "베스킨라빈스 싱글",
  },
  {
    name: "조수",
    date: "8/8",
    reason: "스토어 응모 당첨",
    present: "베스킨라빈스 싱글",
  },
  {
    name: "서유",
    date: "8/8",
    reason: "스토어 응모 당첨",
    present: "올리브영 10000원권",
  },
  {
    name: "김석",
    date: "8/10",
    reason: "스토어 응모 당첨",
    present: "황금 올리브 치킨",
  },
  {
    name: "서유",
    date: "8/20",
    reason: "출석체크 랜덤 선물",
    present: "초코에몽",
  },
  {
    name: "박유",
    date: "8/21",
    reason: "출석체크 랜덤 선물",
    present: "베스킨 라빈스",
  },
  {
    name: "김영",
    date: "8/21",
    reason: "출석체크 랜덤 선물",
    present: "MEGA 커피",
  },
  {
    name: "이예",
    date: "8/22",
    reason: "출석체크 랜덤 선물",
    present: "MEGA 커피",
  },
  {
    name: "연",
    date: "9/7",
    reason: "홍보이벤트 당첨 선물",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "임성",
    date: "9/7",
    reason: "홍보이벤트 당첨 선물",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "박유",
    date: "9/28",
    reason: "스토어 응모 당첨",
    present: "올리브영 10000원권",
  },
  {
    name: "최지",
    date: "10/9",
    reason: "스토어 응모 당첨",
    present: "투썸 10000원권",
  },
  {
    name: "김아",
    date: "10/9",
    reason: "스토어 응모 당첨",
    present: "다이소 5000원권",
  },
  {
    name: "유회",
    date: "10/12",
    reason: "출석체크 당첨 선물",
    present: "초코에몽",
  },
  {
    name: "유회",
    date: "10/15",
    reason: "출석체크 당첨 선물",
    present: "MEGA 커피 깊티",
  },

  {
    name: "수빈",
    date: "10/16",
    reason: "시험기간 랜덤 선물",
    present: "상하이 치킨 스낵랩",
  },
  {
    name: "최재",
    date: "10/16",
    reason: "시험기간 랜덤 선물",
    present: "상하이 치킨 스낵랩",
  },
  {
    name: "정다",
    date: "10/16",
    reason: "시험기간 랜덤 선물",
    present: "상하이 치킨 스낵랩",
  },
  {
    name: "황석",
    date: "10/16",
    reason: "시험기간 랜덤 선물",
    present: "상하이 치킨 스낵랩",
  },
  {
    name: "임하",
    date: "10/16",
    reason: "시험기간 랜덤 선물",
    present: "상하이 치킨 스낵랩",
  },
  {
    name: "오지",
    date: "10/16",
    reason: "시험기간 랜덤 선물",
    present: "상하이 치킨 스낵랩",
  },
  {
    name: "이갑",
    date: "10/17",
    reason: "시험기간 랜덤 선물",
    present: "초코에몽",
  },
  {
    name: "조수",
    date: "10/17",
    reason: "시험기간 랜덤 선물",
    present: "초코에몽",
  },
  {
    name: "김주",
    date: "10/17",
    reason: "시험기간 랜덤 선물",
    present: "초코에몽",
  },
  {
    name: "박주",
    date: "10/17",
    reason: "시험기간 랜덤 선물",
    present: "초코에몽",
  },
  {
    name: "이채",
    date: "10/17",
    reason: "시험기간 랜덤 선물",
    present: "초코에몽",
  },
  {
    name: "하정",
    date: "10/18",
    reason: "출석체크 당첨 선물",
    present: "MEGA 커피 깊티",
  },
  {
    name: "이은",
    date: "10/18",
    reason: "시험기간 랜덤 선물",
    present: "초코 빼빼로",
  },
  {
    name: "현윤",
    date: "10/18",
    reason: "시험기간 랜덤 선물",
    present: "초코 빼빼로",
  },
  {
    name: "김주",
    date: "10/18",
    reason: "시험기간 랜덤 선물",
    present: "초코 빼빼로",
  },
  {
    name: "박주",
    date: "10/18",
    reason: "시험기간 랜덤 선물",
    present: "초코 빼빼로",
  },
  {
    name: "노태",
    date: "10/18",
    reason: "시험기간 랜덤 선물",
    present: "초코 빼빼로",
  },
  {
    name: "조현",
    date: "10/19",
    reason: "시험기간 랜덤 선물",
    present: "페레로로쉐 3구",
  },
  {
    name: "이한",
    date: "10/19",
    reason: "시험기간 랜덤 선물",
    present: "페레로로쉐 3구",
  },
  {
    name: "준석",
    date: "10/19",
    reason: "시험기간 랜덤 선물",
    present: "페레로로쉐 3구",
  },
  {
    name: "한예",
    date: "10/19",
    reason: "시험기간 랜덤 선물",
    present: "페레로로쉐 3구",
  },
  {
    name: "오지",
    date: "10/19",
    reason: "시험기간 랜덤 선물",
    present: "페레로로쉐 3구",
  },
  {
    name: "이예",
    date: "10/20",
    reason: "시험기간 랜덤 선물",
    present: "닥터유에너지바",
  },
  {
    name: "이채",
    date: "10/20",
    reason: "시험기간 랜덤 선물",
    present: "닥터유에너지바",
  },
  {
    name: "예지",
    date: "10/20",
    reason: "시험기간 랜덤 선물",
    present: "닥터유에너지바",
  },
  {
    name: "소윤",
    date: "10/20",
    reason: "시험기간 랜덤 선물",
    present: "닥터유에너지바",
  },
  {
    name: "강승",
    date: "10/20",
    reason: "시험기간 랜덤 선물",
    present: "닥터유에너지바",
  },
  {
    name: "권혜",
    date: "10/21",
    reason: "시험기간 랜덤 선물",
    present: "초코 홈런볼",
  },
  {
    name: "정혜",
    date: "10/21",
    reason: "시험기간 랜덤 선물",
    present: "초코 홈런볼",
  },
  {
    name: "서예",
    date: "10/21",
    reason: "시험기간 랜덤 선물",
    present: "초코 홈런볼",
  },
  {
    name: "임하",
    date: "10/21",
    reason: "시험기간 랜덤 선물",
    present: "초코 홈런볼",
  },
  {
    name: "노태",
    date: "10/21",
    reason: "시험기간 랜덤 선물",
    present: "초코 홈런볼",
  },
  {
    name: "강민",
    date: "10/22",
    reason: "시험기간 랜덤 선물",
    present: "CU 3000원권",
  },
  {
    name: "김지",
    date: "10/22",
    reason: "시험기간 랜덤 선물",
    present: "CU 3000원권",
  },
  {
    name: "예지",
    date: "10/22",
    reason: "시험기간 랜덤 선물",
    present: "CU 3000원권",
  },
  {
    name: "김다",
    date: "10/22",
    reason: "시험기간 랜덤 선물",
    present: "CU 3000원권",
  },
  {
    name: "노태",
    date: "10/22",
    reason: "시험기간 랜덤 선물",
    present: "CU 3000원권",
  },
  {
    name: "이승",
    date: "10/23",
    reason: "홍보 이벤트 선물",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "남궁",
    date: "10/23",
    reason: "홍보 이벤트 선물",
    present: "BBQ 황금올리브 세트",
  },
  {
    name: "김재",
    date: "11/5",
    reason: "출석 당첨 선물",
    present: "초코에몽",
  },
  {
    name: "김무",
    date: "11/5",
    reason: "출석 당첨 선물",
    present: "초코에몽",
  },
  {
    name: "김규",
    date: "11/10",
    reason: "출석 당첨 선물",
    present: "CU 3000원권",
  },
  {
    name: "송유",
    date: "11/18",
    reason: "출석 당첨 선물",
    present: "초코에몽",
  },
  {
    name: "이성",
    date: "11/22",
    reason: "출석 당첨 선물",
    present: "MEGA 커피",
  },
  {
    name: "김민",
    date: "12/4",
    reason: "스토어 응모 선물",
    present: "배민 10000원권",
  },
  {
    name: "권혜",
    date: "12/4",
    reason: "스토어 응모 선물",
    present: "배민 10000원권",
  },
  {
    name: "권혜",
    date: "12/4",
    reason: "스토어 응모 선물",
    present: "배민 10000원권",
  },
  {
    name: "김사",
    date: "12/8",
    reason: "시험기간 이벤트 선물",
    present: "투썸 기프티콘",
  },
  {
    name: "소현",
    date: "12/8",
    reason: "시험기간 이벤트 선물",
    present: "스타벅스 기프티콘",
  },
  {
    name: "김주",
    date: "12/8",
    reason: "시험기간 이벤트 선물",
    present: "할리스 기프티콘",
  },
  {
    name: "김사",
    date: "12/9",
    reason: "시험기간 이벤트 선물",
    present: "탐탐 기프티콘",
  },
  {
    name: "김요",
    date: "12/9",
    reason: "시험기간 이벤트 선물",
    present: "투썸 기프티콘",
  },
  {
    name: "준석",
    date: "12/9",
    reason: "시험기간 이벤트 선물",
    present: "투썸 기프티콘",
  },
  {
    name: "송유",
    date: "12/9",
    reason: "시험기간 이벤트 선물",
    present: "스타벅스 기프티콘",
  },
  {
    name: "이동",
    date: "12/10",
    reason: "스토어 당첨 선물",
    present: "던킨도넛 미니세트",
  },
  {
    name: "박종",
    date: "12/11",
    reason: "스토어 당첨 선물",
    present: "CU 3000원권",
  },
  {
    name: "이승",
    date: "12/11",
    reason: "스토어 당첨 선물",
    present: "CU 3000원권",
  },
];

export const PROMOTION_WIN = [
  {
    month: 9,
    gift: "황금 올리브 치킨 세트",
    winner: [
      { name: "이승", location: "수원" },
      { name: "남궁", location: "수원" },
    ],
    rate: "25%",
  },
  {
    month: 8,
    gift: "황금 올리브 치킨 세트",
    winner: [
      { name: "임성", location: "수원" },
      { name: "연", location: "수원" },
    ],
  },
  {
    month: 7,
    gift: "황금 올리브 치킨 세트",
    winner: [
      { name: "김소", location: "양천" },
      { name: "이승", location: "수원" },
      { name: "송재", location: "양천" },
    ],
  },
];
